name: kos-codex-2 release workflow
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kosdev-code/kos-buildpublish/kos_builder:dockerimage
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      env:
        KOS_KABTOOL_JAR: "/usr/local/lib/kabtool.jar"
        JAVA_CMD: "java"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.event.repository.name }}
          lfs: true

      - name: Extract Version
        run: |
          echo KOSBUILD_VERSION=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV

      - name: Build and Publish
        env:
          KOSBUILD_SECRET_URL: ${{ secrets.KOSBUILD_SECRET_URL }}
          KOSBUILD_SECRET_PASSWORD: ${{ secrets.KOSBUILD_SECRET_PASSWORD }}
        working-directory: ./${{ github.event.repository.name }}
        run: |
          kos_build_handler.sh automation .github/build-release.json
